### ISSUE TITLE
Command "tall-install" is not defined.

### ISSUE THREAD

**Issue by Odilbukh** [ralphjsmit/tall-install#13]
I have run `composer require ralphjsmit/tall-interactive` in my almost fresh Laravel (Filament) project

composer dump-autoload too And when I have run `php artisan tall-install` it returns Error Command "tall-install" is not defined.

Please help to fix it

**Comment by ralphjsmit** [comment]
Hey @Odilbukh, I think you installed the wrong package. You say that you installed `tall-interactive`, but this is the `tall-install` package. I think you should install both packages.

In terms of where to place the `<x-tall-interactive::actionables-manager />` for the Tall Interactive package, you can put that inside the `<body>` tag of the `resources/views/layouts/app.blade.php` view.

Thanks!

**Comment by Odilbukh** [comment]
Thank you!
